POST http://localhost:8080/customers
Content-Type: application/json

{"firstName":  "Mario", "lastName":  "Rossi"}

###

GET http://localhost:8080/customers/1
Accept: application/json

###

POST http://localhost:8080/customers/1/products
Content-Type: application/json

{"name":  "Shampoo"}